### ISSUE TITLE
[1pt] Excessive probes lead to super-slow joins on big cluster

### ISSUE THREAD

**Issue by sharonovd** [tarantool/ansible-cartridge#146]
Post-mortem after 500-nodes cluster deployment

**Comment by dokshina** [comment]
Since we've added possibility to specify role scenario (see #199), it's possible to skip connecting instances to membership.

See [example](https://github.com/tarantool/ansible-cartridge/blob/eb3040d9c1be69655bea4fa509d721a6183868b2/doc/scenario.md#editing-topology-without-connecting-to-membership) too understand how to perform this.

**Comment by sharonovd** [comment]
I expect the following in the docs:
 - measurements on "how long does it take now"
 - starting from what cluster size I should consider skipping this step
