### ISSUE TITLE
[4pt] Add a step to upload TDG config

### ISSUE THREAD

**Issue by no1seman** [tarantool/ansible-cartridge#285]

**Comment by hackallcode** [comment]
# Cartridge Config

Due to historical reasons Cartridge clusterwide configuration has two appearances:
- old-style single-file `config.yml` with all sections combined;
- modern multi-file representation mentioned above. 

There are two options to load the config:
- Lua function `cartridge.config_patch_clusterwide()`;
- Query to `http://ip_address:port/admin/config`.

If single-file `config.yml` is used, you just need to load this file.

If multi-file representation is used, each file should be loaded separately.
In this case, the name of the file will be the name of the section in the config.

# TDG Config

TDG configuration is a folder that contains `config.yml`, which is the entry point.
There may also optionally be:
- `*.avsc` file that contains the model;
- `*.lua` files that contain user code;
- `*.wsdl`, `*.html`, `.json`, `.xml` files used for response templates.

In order to upload this folder to TGD,
you should create a ZIP archive and send it to `http://ip_address:port/admin/config`.

In the future, it will be possible to load the config via Lua: tarantool/tdg2#272

# Role Interface

It is suggested to make 3 options in the config:
- `cartridge_app_config_file`
- `cartridge_app_config_dir`
- `cartridge_app_config_upload_mode`.

If `cartridge_app_config_file` is used, then:
- If the file has the extension `yml`, that file will be uploaded with the
  Lua function `cartridge.config_patch_clusterwide()`;
- If the file has any other extension (it may be better to add whitelist on `zip` and `tar`),
  then this file will be uploaded to `http://localhost:port/admin/config`.

If `cartridge_app_config_dir` is used, one of the following options will be used:
- Each file with an `yml` extension will be loaded in turn to `http://localhost:port/admin/config`
  (`cartridge_app_config_upload_mode: 'yml'`);
- Folder will be archived in `zip`/`tar` archive which will be uploaded to `http://localhost:port/admin/config`
  (`cartridge_app_config_upload_mode: 'zip'` or `cartridge_app_config_upload_mode: 'tar'`).
- Folder will be archived in `zip` archive which will be uploaded to `http://localhost:port/admin/config` or to Lua-function depending on TDG version (`cartridge_app_config_upload_mode: 'tdg'`)

# TDG Example

```yaml
vars:
    cartridge_app_config_dir: '../tdg-app/config'
    cartridge_app_config_upload_mode: 'tdg'
    cartridge_scenario:
     - upload_app_config
```

**Comment by no1seman** [comment]
There are some problems with loading configs via http:
- in the nearest future for security reasons admin may be disabled
- if auth is enabled in TDG we need a token to connect it's an additional artifact and also when botstapping - we don't know it
- http access from CI/CD-runners often blocked for security reasons

**Comment by hackallcode** [comment]
> There are some problems with loading configs via http:
> 
> * in the nearest future for security reasons admin may be disabled
> * if auth is enabled in TDG we need a token to connect it's an additional artifact and also when botstapping - we don't know it
> * http access from CI/CD-runners often blocked for security reasons

I understand these problems, however, the function of loading the config is not exported in TDG, so config cannot be loaded through Lua

**Comment by hackallcode** [comment]
It is also proposed to upload the archive to the machine, and then send the archive to `localhost:port`

**Comment by no1seman** [comment]
@hackallcode In any case if use http - then need to provide token if auth is enabled. It's too much IMHO

**Comment by olegrok** [comment]
> @hackallcode In any case if use http - then need to provide token if auth is enabled. It's too much IMHO

https://github.com/tarantool/tdg2/issues/272 - this task should be done before then
