### ISSUE TITLE
backup must check that cluster is not in resharding phase

### ISSUE THREAD

**Issue by ochaton** [tarantool/ansible-cartridge#419]
Proposal: We should not backup snapshots which were made during resharding process (more over we do not have point-in-time backups yet).

It seems that getting info about rebalancing process from vshard/rebalancer is not enough (it is easy to show a race condition here).

More or less valid way is to get information about statuses of buckets (see: 
 [box.space._bucket.index.status](https://github.com/tarantool/vshard/blob/master/vshard/storage/init.lua#L275))

If we see that any bucket is not in status `active` or `pending` we have to wait until it will get to **proper** state.

I request @Gerold103 help here, what is the safest way to check that rebalancing is not in progress on shard?

**Comment by Gerold103** [comment]
> status active or pending

There is no `pending` status. You probably meant `pinned`?

> what is the safest way to check that rebalancing is not in progress on shard?

`vshard.storage.info().bucket` table should have 0 in all keys except `pinned` and `active`. You can also make a cheap preliminary check using `vshard.storage.rebalancing_is_in_progress()`. It will return true if any rebalancer ops are being applied on the storage right now. Note, that you still will need to check `info().bucket` after that, because there might be `garbage` buckets or `receiving` ones whose receipt has failed, or there could be manual `vshard.storage.bucket_send()` ongoing.

**Comment by opomuc** [comment]
Sorry, the repository is deprecated and the proposed feature will not be implemented.
