### ISSUE TITLE
Support multi-file config uploads

### ISSUE THREAD

**Issue by RunsFor** [tarantool/ansible-cartridge#77]
There is a section in [README](https://github.com/tarantool/ansible-cartridge/blob/master/examples/getting-started-app/README.md#application-configuration) how to apply app configuration. But it only supports inline (one-file) configs.

I want to be able to provide a directory with multi-file config, so cartridge role will archive it and upload into cartridge cluster for me.

**Comment by olegrok** [comment]
Since https://github.com/tarantool/cartridge/issues/523 is not yet implemented. Possible solution is to read files by hand and call config_patch_clusterwide as it is done via graphql endpoint (https://github.com/tarantool/cartridge/pull/402/files#diff-8a8a665a5124cca164e5091223220955R243) in cartridge

**Comment by dokshina** [comment]
Closed via #310
